jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: terraform-docs/gh-actions@main
        with:
          find-dir: .
          git-push: "true"
          output-file: README.md
          output-method: inject
  release:
    needs:
      - docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install the dependencies to the local node_modules folder
        run: npm ci
      - name: Check if the given files are formatted
        run: npx prettier --check .
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Run automated package publishing
        run: npx semantic-release@18
name: release
on:
  push:
    branches:
      - main
